export const translations = {
  en: {
    home: 'Home',
    members: 'Members',
    balanceSheet: 'Balance Sheet',
    disbursement: 'Disbursement',
    payments: 'Payments',
    contact: 'Contact',
    report: 'Report',
    get: 'Get',
    save: 'Save',
    generate: 'Generate',
    loading: 'Loading…',
    saving: 'Saving…',
    generating: 'Generating…',
    generatedSuccess: 'Generated successfully!',
    savedSuccess: 'Saved successfully!',
    addMember: '+ Add Member',
    searchPlaceholder: 'Search members…',
    id: 'ID',
    age: 'Age',
    name: 'Name',
    gender: 'Gender',
    district: 'District',
    mobile: 'Mobile',
    email: 'Email',
    nominee: 'Nominee',
    relation: 'Relation',
    mandal: 'Mandal',
    male: 'Male',
    female: 'Female',
    details: 'Details',
    collection: 'Collection',
    expenses: 'Expenses',
    amount: 'Amount (₹)',
    totalCollection: 'Total Collection',
    totalExpenses: 'Total Expenses',
    grandTotal: 'Grand Total',
    shareAmount: 'Share Amount',
    installment: 'Installment',
    interest: 'Interest',
    ordInstallment: 'Ordinary Installment',
    ordInterest: 'Ordinary Interest',
    speInstallment: 'Special Installment',
    speInterest: 'Special Interest',
    fine: 'Fine',
    otherPayment: 'Other Payment',
    prevMonthBalance: 'Previous Month Balance',
    stationary: 'Stationary',
    salaries: 'Salaries',
    maintainance: 'Maintenance',
    committeeExpenses: 'Committee Expenses',
    communication: 'Communication',
    others: 'Others',
    ordDebit: 'Ordinary Debit',
    speDebit: 'Special Debit',
    disbursements: 'Disbursements',
    pendingAmount: 'Pending Amount',
    member: 'Member',
    jamanat: 'Jamanat',
    ordinaryLoan: 'Ordinary Loan',
    specialLoan: 'Special Loan',
    months: 'Months',
    remarks: 'Remarks',
    sNo: 'SNo',
    action: 'Action',
    paymentsTitle: 'Payments',
    ordDebitGroup: 'Ordinary Debit',
    speDebitGroup: 'Special Debit',
    other: 'Other',
    total: 'Total',
    status: 'Status',
    paid: 'Paid',
    pending: 'Pending',
    wife: 'Wife',
    husband: 'Husband',
    mother: 'Mother',
    father: 'Father',
    sister: 'Sister',
    brother: 'Brother',
    son: 'Son',
    daughter: 'Daughter',
  },
  te: {
    home: 'హోమ్',
    members: 'సభ్యులు',
    balanceSheet: 'బ్యాలెన్స్ షీట్',
    disbursement: 'విత్తరణ',
    payments: 'చెల్లింపులు',
    contact: 'సంప్రదింపు',
    report: 'నివేదిక',
    get: 'తెప్పించు',
    save: 'సేవ్ చేయి',
    generate: 'రూపొందించు',
    loading: 'లోడవుతోంది…',
    saving: 'సేవ్ అవుతోంది…',
    generating: 'రూపొందిస్తోంది…',
    generatedSuccess: 'విజయవంతంగా రూపొందించబడింది!',
    savedSuccess: 'విజయవంతంగా సేవ్ అయింది!',
    addMember: '+ సభ్యుడిని చేర్చు',
    id: 'ఐడి',
    age: 'వయసు',
    searchPlaceholder: 'సభ్యులను వెతకండి…',
    name: 'పేరు',
    gender: 'లింగం',
    district: 'జిల్లా',
    mobile: 'మొబైల్',
    email: 'ఇమెయిల్',
    nominee: 'నామినీ',
    relation: 'సంబంధం',
    mandal: 'మండల్',
    male: 'పురుషుడు',
    female: 'మహిళ',
    details: 'వివరాలు',
    collection: 'సేకరణ',
    expenses: 'ఖర్చులు',
    amount: 'మొత్తం (₹)',
    totalCollection: 'మొత్తం సేకరణ',
    totalExpenses: 'మొత్తం ఖర్చులు',
    grandTotal: 'గ్రాండ్ టోటల్',
    shareAmount: 'వాటా మొత్తం',
    installment: 'వాయిదా',
    interest: 'వడ్డీ',
    ordInstallment: 'సాధారణ వాయిదా',
    ordInterest: 'సాధారణ వడ్డీ',
    speInstallment: 'ప్రత్యేక వాయిదా',
    speInterest: 'ప్రత్యేక వడ్డీ',
    fine: 'జరిమానా',
    otherPayment: 'ఇతర చెల్లింపు',
    prevMonthBalance: 'గత నెల బ్యాలెన్స్',
    stationary: 'స్టేషనరీ',
    salaries: 'జీతాలు',
    maintainance: 'నిర్వహణ',
    committeeExpenses: 'కమిటీ ఖర్చులు',
    communication: 'కమ్యూనికేషన్',
    others: 'ఇతరులు',
    ordDebit: 'సాధారణ డెబిట్',
    speDebit: 'ప్రత్యేక డెబిట్',
    disbursements: 'విత్తరణలు',
    pendingAmount: 'పెండింగ్ మొత్తం',
    member: 'సభ్యుడు',
    jamanat: 'జమానత్',
    ordinaryLoan: 'సాధారణ రుణం',
    specialLoan: 'ప్రత్యేక రుణం',
    months: 'నెలలు',
    remarks: 'వ్యాఖ్యలు',
    sNo: 'క్ర.సం',
    action: 'చర్య',
    paymentsTitle: 'చెల్లింపులు',
    ordDebitGroup: 'సాధారణ డెబిట్',
    speDebitGroup: 'ప్రత్యేక డెబిట్',
    other: 'ఇతరం',
    total: 'మొత్తం',
    status: 'స్థితి',
    paid: 'చెల్లించబడింది',
    pending: 'పెండింగ్',
    wife: 'భార్య',
    husband: 'భర్త',
    mother: 'తల్లి',
    father: 'తండ్రి',
    sister: 'అక్క',
    brother: 'అన్న',
    son: 'కుమారుడు',
    daughter: 'కుమార్తె',
  },
} as const

export type Lang = keyof typeof translations
export type TranslationKey = keyof typeof translations['en']

export function t(lang: Lang, key: TranslationKey): string {
  return (translations[lang] as Record<string, string>)?.[key]
    ?? (translations.en as Record<string, string>)[key]
    ?? key
}
